name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        node: ['16.x', '14.x', '12.x']
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Get Yarn cache directory
        id: yarn_cache_dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn_cache_dir.outputs.dir }}
            node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}-yarn-

      - name: ESLint cache
        uses: actions/cache@v2
        with:
          path: .eslintcache
          key: ${{ runner.os }}-node-${{ matrix.node }}-eslint-${{ hashFiles('.eslintrc.yml') }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}-eslint-${{ hashFiles('.eslintrc.yml') }}-
            ${{ runner.os }}-node-${{ matrix.node }}-eslint-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build

      - name: Run tests
        run: yarn test --colors

      - name: Lint
        run: yarn run lint --cache

      - name: Check formatting
        run: yarn run check-fmt
